name = "gauner-backend"
main = "worker.js"
compatibility_date = "2023-10-30"

# Environment variables (if needed)
# [vars]
# API_KEY = "your-api-key-here"

# Routes (optional - for custom domain)
# routes = [
#   { pattern = "api.gauner.com/*", zone_name = "gauner.com" }
# ]