name = "gauner-backend"
main = "worker.js"
compatibility_date = "2024-01-01"

# Worker configuration
[env.production]
name = "gauner-backend"

# CPU and memory limits (free tier)
cpu_limit = 10
memory_limit = 128

# Routes for the worker
routes = [
  { pattern = "api.gauner.pages.dev/*", zone_name = "pages.dev" }
]